# Data parsing constants
US_STATE_CODE_DICT = {'alabama': 0,
                    'alaska': 1,
                    'arizona': 2,
                    'arkansas': 3,
                    'california': 4,
                    'colorado': 5,
                    'connecticut': 6,
                    'delaware': 7,
                    'florida': 8,
                    'georgia': 9,
                    'hawaii': 10,
                    'idaho': 11,
                    'illinois': 12,
                    'indiana': 13,
                    'iowa': 14,
                    'kansas': 15,
                    'kentucky': 16,
                    'louisiana': 17,
                    'maine': 18,
                    'maryland': 19,
                    'massachusetts': 20,
                    'michigan': 21,
                    'minnesota': 22,
                    'mississippi': 23,
                    'missouri': 24,
                    'montana': 25,
                    'nebraska': 26,
                    'nevada': 27,
                    'new hampshire': 28,
                    'new jersey': 29,
                    'new mexico': 30,
                    'new york': 31,
                    'north carolina': 32,
                    'north dakota': 33,
                    'ohio': 34,
                    'oklahoma': 35,
                    'oregon': 36,
                    'pennsylvania': 37,
                    'rhode island': 38,
                    'south carolina': 39,
                    'south dakota': 40,
                    'tennessee': 41,
                    'texas': 42,
                    'utah': 43,
                    'vermont': 44,
                    'virginia': 45,
                    'washington': 46,
                    'west virginia': 47,
                    'wisconsin': 48,
                    'wyoming': 49,
                    'al': 0,
                    'ak': 1,
                    'az': 2,
                    'ar': 3,
                    'ca': 4,
                    'co': 5,
                    'ct': 6,
                    'de': 7,
                    'fl': 8,
                    'ga': 9,
                    'hi': 10,
                    'id': 11,
                    'il': 12,
                    'in': 13,
                    'ia': 14,
                    'ks': 15,
                    'ky': 16,
                    'la': 17,
                    'me': 18,
                    'md': 19,
                    'ma': 20,
                    'mi': 21,
                    'mn': 22,
                    'ms': 23,
                    'mo': 24,
                    'mt': 25,
                    'ne': 26,
                    'nv': 27,
                    'nh': 28,
                    'nj': 29,
                    'nm': 30,
                    'ny': 31,
                    'nc': 32,
                    'nd': 33,
                    'oh': 34,
                    'ok': 35,
                    'or': 36,
                    'pa': 37,
                    'ri': 38,
                    'sc': 39,
                    'sd': 40,
                    'tn': 41,
                    'tx': 42,
                    'ut': 43,
                    'vt': 44,
                    'va': 45,
                    'wa': 46,
                    'wv': 47,
                    'wi': 48,
                    'wy': 49}

US_NUM_STATES = 50