# Data parsing constants
US_STATE_CODE_DICT = {'alabama': 0,
                    'alaska': 1,
                    'arizona': 2,
                    'arkansas': 3,
                    'california': 4,
                    'colorado': 5,
                    'connecticut': 6,
                    'delaware': 7,
                    'florida': 8,
                    'georgia': 9,
                    'hawaii': 10,
                    'idaho': 11,
                    'illinois': 12,
                    'indiana': 13,
                    'iowa': 14,
                    'kansas': 15,
                    'kentucky': 16,
                    'louisiana': 17,
                    'maine': 18,
                    'maryland': 19,
                    'massachusetts': 20,
                    'michigan': 21,
                    'minnesota': 22,
                    'mississippi': 23,
                    'missouri': 24,
                    'montana': 25,
                    'nebraska': 26,
                    'nevada': 27,
                    'new hampshire': 28,
                    'new jersey': 29,
                    'new mexico': 30,
                    'new york': 31,
                    'north carolina': 32,
                    'north dakota': 33,
                    'ohio': 34,
                    'oklahoma': 35,
                    'oregon': 36,
                    'pennsylvania': 37,
                    'rhode island': 38,
                    'south carolina': 39,
                    'south dakota': 40,
                    'tennessee': 41,
                    'texas': 42,
                    'utah': 43,
                    'vermont': 44,
                    'virginia': 45,
                    'washington': 46,
                    'west virginia': 47,
                    'wisconsin': 48,
                    'wyoming': 49,
                    'al': 0,
                    'ak': 1,
                    'az': 2,
                    'ar': 3,
                    'ca': 4,
                    'co': 5,
                    'ct': 6,
                    'de': 7,
                    'fl': 8,
                    'ga': 9,
                    'hi': 10,
                    'id': 11,
                    'il': 12,
                    'in': 13,
                    'ia': 14,
                    'ks': 15,
                    'ky': 16,
                    'la': 17,
                    'me': 18,
                    'md': 19,
                    'ma': 20,
                    'mi': 21,
                    'mn': 22,
                    'ms': 23,
                    'mo': 24,
                    'mt': 25,
                    'ne': 26,
                    'nv': 27,
                    'nh': 28,
                    'nj': 29,
                    'nm': 30,
                    'ny': 31,
                    'nc': 32,
                    'nd': 33,
                    'oh': 34,
                    'ok': 35,
                    'or': 36,
                    'pa': 37,
                    'ri': 38,
                    'sc': 39,
                    'sd': 40,
                    'tn': 41,
                    'tx': 42,
                    'ut': 43,
                    'vt': 44,
                    'va': 45,
                    'wa': 46,
                    'wv': 47,
                    'wi': 48,
                    'wy': 49}

US_STATE_NAMES = ['alaska',
                'alabama',
                'arkansas',
                'arizona',
                'california',
                'colorado',
                'connecticut',
                'delaware',
                'florida',
                'georgia',
                'hawaii',
                'iowa',
                'idaho',
                'illinois',
                'indiana',
                'kansas',
                'kentucky',
                'louisiana',
                'massachusetts',
                'maryland',
                'maine',
                'michigan',
                'minnesota',
                'missouri',
                'mississippi',
                'montana',
                'north carolina',
                'north dakota',
                'nebraska',
                'new hampshire',
                'new jersey',
                'new mexico',
                'nevada',
                'new york',
                'ohio',
                'oklahoma',
                'oregon',
                'pennsylvania',
                'rhode island',
                'south carolina',
                'south dakota',
                'tennessee',
                'texas',
                'utah',
                'virginia',
                'vermont',
                'washington',
                'wisconsin',
                'west virginia',
                'wyoming']

US_STATE_POSTAL_CODES = ['al',
                        'ak',
                        'az',
                        'ar',
                        'ca',
                        'co',
                        'ct',
                        'de',
                        'fl',
                        'ga',
                        'hi',
                        'id',
                        'il',
                        'in',
                        'ia',
                        'ks',
                        'ky',
                        'la',
                        'me',
                        'md',
                        'ma',
                        'mi',
                        'mn',
                        'ms',
                        'mo',
                        'mt',
                        'ne',
                        'nv',
                        'nh',
                        'nj',
                        'nm',
                        'ny',
                        'nc',
                        'nd',
                        'oh',
                        'ok',
                        'or',
                        'pa',
                        'ri',
                        'sc',
                        'sd',
                        'tn',
                        'tx',
                        'ut',
                        'vt',
                        'va',
                        'wa',
                        'wv',
                        'wi',
                        'wy']

US_STATE_ABBR = ['ala.', 
                'alaska', 
                'ariz.', 
                'ark.', 
                'calif.', 
                'colo.', 
                'conn.', 
                'del.', 
                'd.c.', 
                'fla.', 
                'ga.', 
                'hawaii', 
                'idaho', 
                'ill.', 
                'ind.', 
                'iowa', 
                'kans.', 
                'ky.', 
                'la.', 
                'maine', 
                'md.', 
                'mass.', 
                'mich.', 
                'minn.', 
                'miss.', 
                'mo.', 
                'mont.', 
                'nebr.', 
                'nev.', 
                'n.h.', 
                'n.j.', 
                'n.m.', 
                'n.y.', 
                'n.c.', 
                'n.d.', 
                'ohio', 
                'okla.', 
                'ore.', 
                'pa.', 
                'r.i.', 
                's.c.', 
                's.d.', 
                'tenn.', 
                'tex.', 
                'utah', 
                'vt.', 
                'va.', 
                'wash.', 
                'w.va.', 
                'wis.', 
                'wyo.']

US_NUM_STATES = 50

KEY_WORDS=[
'discrimination',
'hate',
'hatred',
'racism',
'asian hatred',
'racial',
'minorities',
'asian',
'crime'
]